# Generated by Django 5.0.6 on 2026-09-09 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether two-factor authentication (OTP) is enabled for this user.', verbose_name='two-factor authentication'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login Verification'), ('CHANGE_2FA', '2FA Setting Change')], db_index=True, default='LOGIN', max_length=30, verbose_name='purpose')),
                ('code_hash', models.CharField(db_index=True, help_text='HMAC-SHA256 hex digest of the raw 6-digit code.', max_length=64, verbose_name='code hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('used', models.BooleanField(default=False, verbose_name='used')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of failed verification attempts.', verbose_name='verification attempts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
