# Generated by Django 5.0.6 on 2026-09-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_two_factor_enabled_otp'),
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='firm.firm', verbose_name='firm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('FIRM_ADMIN', 'Firm Admin'), ('LAWYER', 'Lawyer'), ('CLERK', 'Clerk'), ('CLIENT', 'Client')], db_index=True, default='CLERK', max_length=20, verbose_name='role'),
        ),
    ]
