# Generated by Django 5.0.6 on 2026-09-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='firm name')),
                ('registration_number', models.CharField(blank=True, default='', max_length=100, verbose_name='registration/license number')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='firm email')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='phone number')),
                ('address', models.TextField(blank=True, default='', verbose_name='address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this firm is active.', verbose_name='active status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'firm',
                'verbose_name_plural': 'firms',
                'ordering': ['-created_at'],
            },
        ),
    ]
