# Generated by Django 5.0.6 on 2026-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('MULTI', 'Multi')], db_index=True, default='MULTI', help_text='Designates whether this firm is individual (solo practitioner) or multi-lawyer.', max_length=20, verbose_name='firm type'),
        ),
    ]
