# Generated by Django 5.0.6 on 2026-09-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='full name')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A lead with this email address already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=30, verbose_name='phone number')),
                ('address', models.TextField(blank=True, default='', verbose_name='address')),
                ('interest', models.CharField(choices=[('register', 'Register'), ('inquiry', 'Inquiry'), ('other', 'Other')], db_index=True, max_length=30, verbose_name='interest')),
                ('interested_firm', models.CharField(choices=[('individual', 'Individual'), ('multi', 'Multi')], db_index=True, max_length=30, verbose_name='interested firm type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('meeting_scheduled', 'Meeting Scheduled'), ('confirmed', 'Confirmed')], db_index=True, default='pending', max_length=30, verbose_name='lead status')),
                ('preferred_time', models.CharField(choices=[('8-10', '8-10'), ('10-12', '10-12'), ('12-02', '12-02'), ('02-04', '02-04'), ('04-06', '04-06'), ('06-08', '06-08'), ('08-10', '08-10')], max_length=30, verbose_name='preferred time for contact')),
                ('preferred_contact_way', models.CharField(choices=[('phone_call', 'Phone Call'), ('whatsapp', 'WhatsApp')], max_length=30, verbose_name='preferred contact way')),
                ('notes', models.TextField(blank=True, default='', verbose_name='admin internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
