# Generated by Django 5.0.6 on 2026-09-17 11:54

import apps.matters.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firm', '0001_initial'),
        ('lawyer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='matter title')),
                ('case_number', models.CharField(db_index=True, default=apps.matters.models.generate_case_number, max_length=100, unique=True, verbose_name='case number')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30, verbose_name='status')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='priority')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='due date')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='lawyer.client', verbose_name='client')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='firm.firm', verbose_name='firm')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to=settings.AUTH_USER_MODEL, verbose_name='assigned lawyer')),
            ],
            options={
                'verbose_name': 'matter',
                'verbose_name_plural': 'matters',
                'ordering': ['-created_at'],
            },
        ),
    ]
