# Generated by Django 5.0.6 on 2026-09-21 03:01

import apps.subscription.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firm', '0002_firm_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='plan name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='billing cycle')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is active and available for new subscriptions.', verbose_name='active status')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this plan is publicly visible to prospective customers.', verbose_name='public visibility')),
                ('is_popular', models.BooleanField(default=False, help_text='Designates whether this plan is highlighted as popular (one at a time).', verbose_name='popular badge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='completed', max_length=20, verbose_name='transaction status')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='transaction date')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='online', max_length=20, verbose_name='payment method')),
                ('transaction_id', models.CharField(db_index=True, default=apps.subscription.models.generate_transaction_id, max_length=100, unique=True, verbose_name='transaction ID')),
                ('sender_bank_account', models.CharField(blank=True, default='', max_length=100, verbose_name='sender bank account')),
                ('receiver_bank_account', models.CharField(blank=True, default='', max_length=100, verbose_name='receiver bank account')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='firm.firm', verbose_name='firm')),
                ('firm_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='firm admin')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('pending', 'Pending')], db_index=True, default='active', max_length=20, verbose_name='subscription status')),
                ('is_trial', models.BooleanField(default=False, verbose_name='is trial')),
                ('trial_duration_days', models.PositiveIntegerField(default=0, verbose_name='trial duration in days')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='trial ends at')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='started at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20, verbose_name='subscription type')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='canceled at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='firm.firm', verbose_name='firm')),
                ('firm_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='firm admin')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.plan', verbose_name='plan')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscription.transaction', verbose_name='payment transaction')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
